#!/bin/bash

rm -rf ~/AUTO-TOOL.V3
rm -rf /sdcard/AUTO-TOOL.V3

mkdir -p /sdcard/AUTO-TOOL.V3/CONFIG
mkdir -p /sdcard/AUTO-TOOL.V3/output/SKIN
mkdir -p /sdcard/AUTO-TOOL.V3/PAK
mkdir -p /sdcard/AUTO-TOOL.V3/REPACK

touch /sdcard/AUTO-TOOL.V3/ID.txt

cd ~ || exit

git clone https://github.com/ТВОЙ_РЕПОЗИТОРИЙ/AUTO-TOOL.git

mv auto AUTO-TOOL.V3

chmod +x AUTO-TOOL.V3/*

./auto
